substitutions:
  inverter_id: inverter
  updates: 5s
  api_key: "pJ+1diNeePHmj/5EGNAGLSV76ngR1gtpKeZkvC1o7QY="
  ota_password: "2ea87526fba5ac621872aa7de04e2299"

esphome:
  name: inverter-monitor
  comment: "Inverter monitor"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# INFO is better for ESP perfomance, change to DEBUG if you have any issues
logger:
  level: INFO  

api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

web_server:
  port: 80    

uart:
  - id: uart_inverter
    baud_rate: 19200
    tx_pin: GPIO18
    rx_pin: GPIO19
    stop_bits: 1
    parity: NONE
    data_bits: 8
    debug:
      direction: BOTH
      dummy_receiver: false

modbus:
  - id: modbus_inverter
    uart_id: uart_inverter
    send_wait_time: 200ms

modbus_controller:
  - id: must_inverter
    address: 0x04
    modbus_id: modbus_inverter
    command_throttle: 200ms
    setup_priority: -10
    update_interval: ${updates}

sensor:

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""      

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25205
    name: "Inverter Battery Voltage"
    register_type: holding
    unit_of_measurement: "V"
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25206
    name: "Inverter Voltage"
    register_type: holding
    unit_of_measurement: "V"
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25207
    name: "Inverter Grid voltage"
    register_type: holding
    unit_of_measurement: "V"
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25209
    name: "Inverter Control current"
    register_type: holding
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:current-dc
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25210
    name: "Inverter Current"
    register_type: holding
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:current-dc
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25211
    name: "Inverter Grid current"
    register_type: holding
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25212
    name: "Inverter Load current"
    register_type: holding
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
      multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25213
    value_type: S_WORD
    name: "Inverter Power"
    register_type: holding
    unit_of_measurement: "W"
    accuracy_decimals: 1
    icon: mdi:flash

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25214
    name: "Inverter Grid power"
    register_type: holding
    unit_of_measurement: "W"
    accuracy_decimals: 1
    value_type: S_WORD
    icon: mdi:flash

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25215
    name: "Inverter Load power"
    register_type: holding
    unit_of_measurement: "W"
    accuracy_decimals: 1
    icon: mdi:flash

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25216
    name: "Inverter System load"
    register_type: holding
    unit_of_measurement: "%"
    accuracy_decimals: 1
    icon: mdi:flash

  - platform: modbus_controller
    address: 25226
    name: "Inverter Grid frequency"
    register_type: holding
    accuracy_decimals: 2
    unit_of_measurement: "Hz"
    filters:
      multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25233
    register_type: holding
    name: "Inverter temp AC radiator"
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    icon: mdi:temperature-celsius

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25235
    register_type: holding
    name: "Inverter temp DC Radiator "
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:temperature-celsius 

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 15201
    name: "Inverter PV Charger Workstate"
    register_type: holding

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 15203
    name: "Inverter charging state"
    register_type: holding  

# Inverter Accumulated discharge power
  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25247
    register_type: holding
    id: discharger_total_mwh
    internal: true

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25248
    register_type: holding
    id: discharger_total_kwh
    internal: true
    filters:
      multiply: 0.1

  - platform: template
    name: "Inverter Accumulated discharger power"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    lambda: !lambda 'return (id(discharger_total_mwh).state * 1000.0 + id(discharger_total_kwh).state);'

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25249
    register_type: holding
    id: buy_mwh
    internal: true
  
  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25250
    register_type: holding
    id: buy_kwh
    internal: true
    filters:
      multiply: 0.1
  
  - platform: template
    name: "Inverter Accumulated buy power"
    unit_of_measurement: kWh
    lambda: |-
     return (id(buy_mwh).state * 1000.0 + id(buy_kwh).state);
    accuracy_decimals: 1

# Inverter Accumulated load power
  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25253
    register_type: holding
    id: load_mwh
    internal: True

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25254
    register_type: holding
    id: load_kwh
    internal: True
    filters:
      multiply: 0.1
  
  - platform: template
    name: "Inverter Accumulated load power"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    lambda: !lambda return (id(load_mwh).state * 1000.0 + id(load_kwh).state);

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25273
    register_type: holding
    value_type: S_WORD
    name: "Inverter Battery power"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    icon: mdi:flash

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 25274
    register_type: holding
    value_type: S_WORD
    name: "Inverter Battery current"
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:current-dc

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: Charger_workstate1
    name: "Inverter Charger workstate1"
    address: 15201
    register_type: holding
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("PowerOn");
          case 1: return std::string("Selftest Mode");
          case 2: return std::string("OffGrid");
          case 3: return std::string("Grid-Tie");
          case 4: return std::string("ByPass");
          case 5: return std::string("Stop");
          case 6: return std::string("Grid charging");
          default: return std::string("Unknown");
        }
 #       return x;

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: charging_state1
    name: "Inverter charging state1"
    address: 15203
    register_type: holding
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("Stop");
          case 1: return std::string("Absorb charge");
          case 2: return std::string("Float charge");
          case 3: return std::string("EQ charge");
          default: return std::string("Unknown");
        }
#        return x;

select:
  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: energy_use_mode
    name: "Inverter Energy use mode (parameter 00)"
    address: 20109
    optionsmap:
      "SBU (Solar/battery/utility)": 1
      "SUB (Solar/utility/battery)": 2
      "UTI (Utility only)": 3
      "SOL (Solar only)": 4

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: charger_source_priority
    name: "Inverter Charger source priority (parameter 10)"
    address: 20143
    optionsmap:
      "CSO (Solar first)": 0
      "SNU (Solar and utility)": 2
      "OSO (Solar only)": 3

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    address: 20111
    id: inverter_ac_input_voltage_range
    name: "Inverter AC input voltage range (02)"
    optionsmap:
      "VDE (184-253VAC)": 0
      "UPS (170-280VAC)": 1
      "APL (90-280VAC)": 2
      "GEN (Generator)": 3

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: grid_max_charge_current
    name: "Inverter Grid Max Charge"
    address: 20125
    value_type: U_WORD
    optionsmap:
      "10 A": 100
      "20 A": 200
      "30 A": 300
      "40 A": 400
      "50 A": 500
      "60 A": 600
      "70 A": 700

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: absorb_charge_current
    name: "Inverter Absorb Charge"
    address: 20126
    value_type: U_WORD
    optionsmap:
      "10 A": 100
      "20 A": 200
      "30 A": 300

number:
 
  - platform: modbus_controller
    id: batt_float_voltage
    name: "Inverter Float voltage"
    unit_of_measurement: "V"
    address: 10103
    value_type: U_WORD
    min_value: 13.0
    max_value: 14.0
    step: 0.1
    mode: box
    lambda: "return x * 0.1; "
    write_lambda: |-
      return x * 10 ;

  - platform: modbus_controller
    id: batt_absorb_voltage
    name: "Inverter Absorb voltage"
    unit_of_measurement: "V"
    address: 10104
    min_value: 13.4
    max_value: 14.2
    step: 0.1
    mode: box    
    value_type: U_WORD
    lambda: "return x * 0.1; "
    write_lambda: |-
      return x * 10 ;

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: batt_stop_dischg
    name: "Inverter Battery stop discharging voltage"
    unit_of_measurement: "V"
    address: 20118
    value_type: U_WORD
    min_value: 10.0
    max_value: 13.2
    step: 0.1
    mode: box
    lambda: "return x * 0.1;"
    write_lambda: |-
      return x * 10;

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: batt_stop_chg
    name: "Inverter Battery stop charging voltage"
    unit_of_measurement: "V"
    address: 20119
    value_type: U_WORD
    min_value: 13.2
    max_value: 14.4
    step: 0.1
    mode: box
    multiply: 10 

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: batt_low_voltage
    name: "Inverter Battery low voltage"
    unit_of_measurement: "V"
    address: 20127
    value_type: U_WORD
    min_value: 10.0
    max_value: 12.5
    step: 0.1
    mode: box
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: must_inverter
    id: batt_high_voltage
    name: "Inverter Battery high voltage"
    unit_of_measurement: "V"
    address: 20128
    value_type: U_WORD
    min_value: 13.8
    max_value: 14.8
    step: 0.1
    mode: box
    multiply: 10


