esphome:
  name: termostat
  friendly_name: Termostat

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: "L7sxywpOdm0G4gLcIM+5I4cSBzz0cku1zITW6rUI5fQ="

ota:
  - platform: esphome
    password: "cecaf292577f10925f447fd6cf54f69e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80

# =======================
# ONE-WIRE BUS
# =======================
one_wire:
  - platform: gpio
    pin: GPIO23
    id: ow_bus

# =======================
# SENSORS
# =======================
sensor:
  - platform: uptime
    name: "Uptime Seconds"
    id: uptime_sensor
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    unit_of_measurement: "%"
    entity_category: diagnostic
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);

# =======================
# DS18B20 SENSORS (для временного теста)
# =======================
  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x2f00000074c28428
    name: "Температура 1"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x1a0000007389f228
    name: "Температура 2"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x8c0000007501d628
    name: "Температура 3"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x6700000077041e28
    name: "Температура 4"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0xd100000077ab9e28
    name: "Температура 5"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x90000000754ad128
    name: "Температура 6"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0xf900000077c00528
    name: "Температура 7"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x3000000076fd5528
    name: "Температура 8"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x4700000074c2b328
    name: "Температура 9"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s

  - platform: dallas_temp
    one_wire_id: ow_bus
    address: 0x2300000074cf5b28
    name: "Температура 10"
    resolution: 12
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 3
    update_interval: 3s


# =======================
# SWITCH
# =======================
switch:
  - platform: gpio
    id: boiler_relay
    name: "Реле котла"
    pin:
      number: GPIO22
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF

# =======================
# TEXT SENSOR
# =======================
text_sensor:
  - platform: template
    name: "Uptime (formatted)"
    update_interval: 60s
    icon: "mdi:clock-outline"
    lambda: |-
      int seconds = (int) id(uptime_sensor).state;
      int days = seconds / 86400;
      int hours = (seconds % 86400) / 3600;
      int minutes = (seconds % 3600) / 60;
      char buffer[32];
      sprintf(buffer, "%dd %02dh %02dm", days, hours, minutes);
      return std::string(buffer);
